### ISSUE TITLE
Bug: Search does not function on retainer inventory

### ISSUE THREAD

**Issue by n3farious** [Tischel/InventorySearchBar#10]
Expected Behavior: 
- Open retainer
- Select Entrust or Withdraw
- Click on retainer inventory window
- Press Ctrl-F to display search field

Actual Behavior:
- Search bar does not display on retainer inventory. It opens correctly on inventory and saddlebags.

Dalamud Core D7.4.1.0
Inventory Search Bar 1.1.0.0

**Comment by n3farious** [comment]
More info.. I use "Expanded" inventory interface in Character Configuration.

I found the search bar, but it does not display on the first tab of the retainer at all.. only on the second or third of three.

**Comment by drejjmit** [comment]
Same, you can search from Second window, and that search first and second window but not third

**Comment by Tischel** [comment]
Fixed in v1.1.0.1
