### ISSUE TITLE
Bug: Search result highlighting/shading is erratic

### ISSUE THREAD

**Issue by n3farious** [Tischel/InventorySearchBar#11]
Expected behavior: 
- Enter search criteria in search bar
- Inventory should be shaded except for search results
- Shading and search results should reset after closing inventory

Observed behavior:
- Shading and highlighting does not occur until selecting another tab in inventory.
- Closing and re-opening inventory incorrectly retains shading/highlighting until selecting another tab.

**Comment by Tischel** [comment]
Fixed in v1.1.0.1
