### ISSUE TITLE
Bug: Search Results are inconsistent on retainers

### ISSUE THREAD

**Issue by n3farious** [Tischel/InventorySearchBar#12]
Results seem unpredictable on retainers currently. 

In this example, text search for ore, which most of the left-most bag contains. Only some ore is highlighted, but other items that don't contain ore in their name are. 

![image](https://user-images.githubusercontent.com/14372366/212939300-186bf444-c6ee-494e-9f76-bb10b04249cb.png)

**Comment by n3farious** [comment]
Additional information. It seems that the 1st of my 5 retainers work correctly.
The other 4 retainers will highlight the correct number of found items, but in the wrong positions. 
ie: I search for "electrum" and it highlights two items which are not electrum.  Search for "raw", of which I have 6 contiguous slots, then a random 6 items are highlighted, none containing "raw".

**Comment by Tischel** [comment]
Fixed in v1.1.0.2
