### ISSUE TITLE
Option to set up/down position and not just right/left

### ISSUE THREAD

**Issue by drejjmit** [Tischel/InventorySearchBar#3]
So it doesn't make this part of the "Items" and "Key Items & Crystals" unclickable. 
![image](https://user-images.githubusercontent.com/15526476/187635427-d16ac91b-c72a-4dc8-ac61-617445e6c0e2.png)
I know it's just a small area that becomes unclickable.. but it's exactly where i've clicked for years ☹️

**Comment by Tischel** [comment]
I've fixed the "invisible area" below the search bar in v0.5.0.0
