### ISSUE TITLE
Frame drops in old lib

### ISSUE THREAD

**Issue by drejjmit** [Tischel/InventorySearchBar#4]
There were some lag issues fixed in the ``CriticalCommonLib``. Do you mind releasing a version with these fixes?
https://github.com/Critical-Impact/InventoryTools/issues/142
https://github.com/Critical-Impact/CriticalCommonLib/commit/50a1c326793b2b3c5b13ba581b5efeabbcd6b0bc

**Comment by Tischel** [comment]
Thanks for letting me know, I'll release an update ASAP

**Comment by Tischel** [comment]
Fixed in v0.5.0.0
