### ISSUE TITLE
Doesn't work if "Keybind only" is disabled

### ISSUE THREAD

**Issue by drejjmit** [Tischel/InventorySearchBar#6]
After update, the search bar doesn't show up if you open the Inventory with ``Keybind only`` unchecked.
I can only trigger the search bar if i have ``Keybind only`` on and i press the keybind.

Downgrading to v1.0.0.0 make the search bar re-appear 
![image](https://user-images.githubusercontent.com/15526476/194065975-ee997c74-498f-4a9e-9b34-90828a1f8790.png)

**Comment by Tischel** [comment]
Fixed in v1.0.0.2
