### ISSUE TITLE
[Bug] Search results not persistent when changing retainer inventory tabs

### ISSUE THREAD

**Issue by n3farious** [Tischel/InventorySearchBar#7]
Environment: 
- Inventory Search Bar Version: 1.0.0.2
- Dalamud Core Version: 7.0.0.8

Expected Behavior:
- Search for item, resulting item location is highlighted, change to the highlighted tab and results should remain highlighted.

Current Behavior:
- Search for item not on current tab
- Click on a tab that has highlight with the resulting item
- Search bar and highlighting is now reset
- Must re-do search while on tab

**Comment by Tischel** [comment]
Fixed in v1.0.0.3
